import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopHeaderNotification from "@/components/Elements/TopHeaderNotification";
import DesktopNavBar from "@/components/Desktop/DesktopNavBar";
import { PROJECT_NAME } from "../../config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: `${PROJECT_NAME}`,
  description: "Generated by Sakar Khadak Using Next Js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="hidden md:block">
          <TopHeaderNotification />
          <DesktopNavBar />
        </div>
        {children}
      </body>
    </html>
  );
}
