export const allProduct = [
  {
    id: 1,
    image: "/productImg1.webp",
    title: "Bus Mania : Station Shuffle Game Buy Unity Source Code",
    category: "Web Template",
    price: "15",
    inStock: 5,
    featured: true,
    slug: "bus-mania-station-shuffle-game-buy-unity-source-code",
  },
  {
    id: 2,
    image: "/productImg2.png",
    title: "Deliver It 3D Game Unity 3D Source Code",
    category: "Game Template",
    price: "20",
    inStock: 3,
    slug: "deliver-it-3d-game-unity-3d-source-code",
  },
  {
    id: 3,
    image: "/productImg3.webp",
    title: "Human vs Alien – Multiplayer Game Buy Unity Source Code",
    category: "Web Template",
    price: "25",
    inStock: 7,
    slug: "human-vs-alien-multiplayer-game-buy-unity-source-code",
  },
  {
    id: 4,
    image: "/productImg4.webp",
    title: "Metal Black OPS Game Buy Unity Source Code",
    category: "Game Template",
    price: "10",
    inStock: 2,
    slug: "metal-black-ops-game-buy-unity-source-code",
  },
  {
    id: 5,
    image: "/productImg5.webp",
    title: "Tactical Knight Game – Buy Unity Games",
    category: "Web Template",
    price: "18",
    inStock: 6,
    featured: true,
    slug: "tactical-knight-game-buy-unity-games",
  },
  {
    id: 6,
    image: "/productImg6.webp",
    title: "New Year Simulation Bundle 10 Best Unity Game Source Code",
    category: "Game Template",
    price: "16",
    inStock: 4,
    featured: true,
    slug: "new-year-simulation-bundle-10-best-unity-game-source-code",
  },
  {
    id: 7,
    image: "/productImg7.webp",
    title: "Santa's Christmas Bundle Top 10 Unity Game Source Code",
    category: "Web Template",
    price: "16",
    inStock: 8,
    slug: "santas-christmas-bundle-top-10-unity-game-source-code",
  },
  {
    id: 8,
    image: "/productImg8.webp",
    title: "Summer Special Deal 30 Unity Source Code Bundle",
    category: "Game Template",
    price: "26",
    inStock: 3,
    featured: true,
    slug: "summer-special-deal-30-unity-source-code-bundle",
  },
  {
    id: 9,
    image: "/productImg9.webp",
    title: "Ultimate Winter Deal Get 100 Plus Games",
    category: "Web Template",
    price: "16",
    inStock: 5,
    slug: "ultimate-winter-deal-get-100-plus-games",
  },
  {
    id: 10,
    image: "/productImg10.webp",
    title: "Unity Hyper Pack 17 Games Source Code Deal",
    category: "Game Template",
    price: "30",
    inStock: 2,
    slug: "unity-hyper-pack-17-games-source-code-deal",
  },
  {
    id: 11,
    image: "/productImg11.webp",
    title: "Buy Unity Source Code | Empire.io",
    category: "Web Template",
    price: "15",
    inStock: 6,
    featured: true,
    slug: "buy-unity-source-code-empireio",
  },
  {
    id: 12,
    image: "/productImg12.webp",
    title: "Buy Unity Games | Draw Puzzle Story",
    category: "Game Template",
    price: "20",
    inStock: 4,
    slug: "buy-unity-games-draw-puzzle-story",
  },
  {
    id: 13,
    image: "/productImg13.webp",
    title: "Buy Unity Games | Dead Flip Challenge",
    category: "Web Template",
    price: "25",
    inStock: 7,
    slug: "buy-unity-games-dead-flip-challenge",
  },
  {
    id: 14,
    image: "/productImg14.webp",
    title: "Circus Dart Wheel Game – Unity Games Source Code",
    category: "Game Template",
    price: "10",
    inStock: 3,
    slug: "circus-dart-wheel-game-unity-games-source-code",
  },
  {
    id: 15,
    image: "/productImg15.webp",
    title: "Chop & Mine Idle Game – Buy Unity Source Code",
    category: "Web Template",
    price: "18",
    inStock: 5,
    featured: true,
    slug: "chop-mine-idle-game-buy-unity-source-code",
  },
  {
    id: 16,
    image: "/productImg16.webp",
    title: "Block Shooter Game – Buy Unity Source Code",
    category: "Game Template",
    price: "16",
    inStock: 2,
    slug: "block-shooter-game-buy-unity-source-code",
  },
  {
    id: 17,
    image: "/productImg17.webp",
    title: "Brain Master Puzzle Game – Buy Unity Game Source Code",
    category: "Web Template",
    price: "16",
    inStock: 6,
    featured: true,
    slug: "brain-master-puzzle-game-buy-unity-game-source-code",
  },
  {
    id: 18,
    image: "/productImg18.webp",
    title: "Ball Thrower Game – Buy Unity Source Code",
    category: "Game Template",
    price: "26",
    inStock: 4,
    featured: true,
    slug: "ball-thrower-game-buy-unity-source-code",
  },
  {
    id: 19,
    image: "/productImg19.webp",
    title: "Big Head Game – Buy Unity Source Code",
    category: "Web Template",
    price: "16",
    inStock: 8,
    featured: true,
    slug: "big-head-game-buy-unity-source-code",
  },
  {
    id: 20,
    image: "/productImg20.webp",
    title: "Squid Game 7 Challenge Game Buy Unity Source Code",
    category: "Game Template",
    price: "30",
    inStock: 3,
    slug: "squid-game-7-challenge-game-buy-unity-source-code",
  },
];
